version: '3'
services:
  api:
    container_name: restful_api
    build: ./api
    ports:
      - "3333:3333"
  nginx:
    container_name: webserver
    build:
     context: ./
     dockerfile: ./nginx/Dockerfile
    depends_on:
      - api
    volumes:
     - ./nginx/nginx-app.template:/etc/nginx/conf.d/nginx-app.template
    ports:
     - "80:80"
    environment:
     - NGINX_PORT=80
    command: /bin/sh -c "envsubst '$$NGINX_PORT' < /etc/nginx/conf.d/nginx-app.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
